version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8007
    volumes:
      - ./:/usr/src/ludo/
    ports:
      - 8007:8007
    env_file:
      - .env.compose
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=ludo
      - POSTGRES_PASSWORD=ludo
      - POSTGRES_DB=ludo_dev
  fake-siu:
    build: fake-siu
    stop_grace_period: 1s
    ports:
      - 3000:3000

volumes:
  postgres_data:
