from .base_view import BaseViewSet
from .commission_teacher_views import CommissionTeacherViewSet
from .commission_views import CommissionViewSet
from .commissionInscription_views import CommissionInscriptionViewSet
from .custom_gcm_device_viewset import CustomGCMDeviceViewSet
from .evaluation_submission_student_views import EvaluationSubmissionViewSet
from .evaluation_submission_teacher_views import \
    EvaluationSubmissionTeacherViewSet
from .evaluation_teacher_views import EvaluationTeacherViewSet
from .evaluation_views import EvaluationViewSet
from .final_exam_student_views import FinalExamStudentViewSet
from .final_exam_teacher_views import FinalExamTeacherViews
from .final_teacher_views import FinalTeacherViewSet
from .semester_views import SemesterViewSet
from .student_views import StudentViews
from .subject_views import SubjectViewSet
