from .views.subject_views_tests import SubjectViewsTests
from .views.final_exam_student_views_tests import StudentFinalExamViewsTests
from .views.final_exam_teacher_views_tests import TeacherFinalExamViewsTests

