from .views.subject_views_tests import SubjectViewsTests
from .views.student_final_exam_views_tests import StudentFinalExamViewsTests
from .views.teacher_final_exam_views_tests import TeacherFinalExamViewsTests

