# Generated by Django 3.1.1 on 2020-09-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encodings',
            field=models.JSONField(default=dict),
        ),
    ]
