# Generated by Django 3.0.1 on 2020-01-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
