# Generated by Django 3.1.1 on 2020-10-09 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='year_in_school',
            field=models.CharField(choices=[('OP', 'Open'), ('PA', 'Pending Act'), ('AS', 'Act Sent')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='face_encodings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
