# Generated by Django 3.0.2 on 2020-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200225_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='correlatives',
            field=models.ManyToManyField(blank=True, to='backend.Subject'),
        ),
    ]
