# Generated by Django 3.0.1 on 2020-01-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200115_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
