# Generated by Django 3.1.2 on 2020-11-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201026_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='siu_id',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
