# Generated by Django 3.1.1 on 2020-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_face_encodings'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='year_in_school',
            field=models.CharField(choices=[('OP', 'Open'), ('PA', 'Pending Act'), ('AS', 'Act Sent')], default='OP', max_length=2),
        ),
    ]
