# Generated by Django 3.1.2 on 2020-10-15 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201009_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_encodings',
        ),
        migrations.AddField(
            model_name='student',
            name='face_encodings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
