# Generated by Django 3.1.2 on 2020-10-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201015_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final',
            name='course',
        ),
        migrations.RemoveField(
            model_name='final',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='final',
            name='siu_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
