# Generated by Django 3.0.2 on 2020-02-25 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200225_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalexam',
            name='grade',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
