# Generated by Django 3.1.2 on 2020-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_teacher_siu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='final',
            name='subject_siu_id',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
