# Generated by Django 3.1.2 on 2021-01-12 20:01

import backend.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201201_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalToApprove',
            fields=[
            ],
            options={
                'verbose_name': 'Final Date to Approve',
                'verbose_name_plural': 'Final Dates to Approve',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.final',),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Staff User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.user',),
            managers=[
                ('objects', backend.models.user.CustomUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='preregisteredstudent',
            options={'verbose_name': 'Pre Registered Student'},
        ),
    ]
