# Generated by Django 3.1.2 on 2020-10-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201020_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='siu_id',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
