# Generated by Django 3.1.2 on 2021-01-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210112_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='act',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='status',
            field=models.CharField(choices=[('DF', 'DF'), ('RJ', 'RJ'), ('OP', 'OP'), ('PA', 'PA'), ('AS', 'AS')], default='OP', max_length=2),
        ),
    ]
