# Generated by Django 3.0.2 on 2020-03-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='teacher',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='backend.Teacher'),
            preserve_default=False,
        ),
    ]
