# Generated by Django 3.0.2 on 2020-03-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_final_teacher'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='finalexam',
            constraint=models.UniqueConstraint(fields=('final', 'student'), name='one_final_exam_per_student'),
        ),
    ]
