# Generated by Django 3.1.2 on 2021-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210114_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='siu_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='status',
            field=models.CharField(choices=[('DF', 'DF'), ('RJ', 'RJ'), ('OP', 'OP'), ('PA', 'PA'), ('AS', 'AS')], default='DF', max_length=2),
        ),
    ]
