# Generated by Django 3.1.2 on 2021-01-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject_siu_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
