# Generated by Django 3.0.2 on 2020-04-22 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200401_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals', to='backend.Subject'),
        ),
        migrations.AlterField(
            model_name='final',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals', to='backend.Teacher'),
        ),
        migrations.AlterField(
            model_name='finalexam',
            name='final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='backend.Final'),
        ),
        migrations.AlterField(
            model_name='finalexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='backend.Student'),
        ),
    ]
