# Generated by Django 3.1.2 on 2021-02-01 23:16

import backend.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210201_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalexam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='finalexam',
            name='final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='backend.final', verbose_name='Final'),
        ),
        migrations.AlterField(
            model_name='finalexam',
            name='grade',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='finalexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='backend.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='finalexam',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='student',
            name='padron',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Padrón'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='legajo',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Legajo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, unique=True, validators=[backend.validators.validate_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Es estudiante?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Es docente?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actualización'),
        ),
    ]
