# Generated by Django 3.0.2 on 2020-04-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='correlatives',
        ),
    ]
