# Generated by Django 3.0.2 on 2020-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_course_correlatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inscripto',
            field=models.BooleanField(default=False),
        ),
    ]
