# Generated by Django 3.1.2 on 2021-04-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
