# Generated by Django 3.1.2 on 2021-04-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
