# Generated by Django 3.1.2 on 2021-08-05 00:58

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_final_subject_name'),
    ]

    operations = [
        UnaccentExtension()
    ]
