# Generated by Django 3.1.2 on 2023-08-26 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210805_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_siu_id', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='SIU ID de Materia')),
                ('subject_name', models.CharField(db_index=True, editable=False, max_length=100, verbose_name='Nombre de Materia')),
                ('siu_id', models.IntegerField(db_index=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('chief_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='backend.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
    ]