# Generated by Django 3.1.2 on 2023-09-02 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_moment', models.CharField(choices=[('FS', 'FS'), ('SS', 'SS'), ('IW', 'IW'), ('IS', 'IS')], default='FS', max_length=2, verbose_name='Momento del año')),
                ('start_date', models.DateTimeField(db_index=True, verbose_name='Fecha de inicio')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='backend.commission', verbose_name='Semestres')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
    ]