# Generated by Django 3.1.2 on 2023-10-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'P'), ('A', 'A'), ('C', 'C'), ('R', 'R')], default='P', max_length=1, verbose_name='Estado')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Inscripcion a Cursada',
                'verbose_name_plural': 'Inscripciones a Cursadas',
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='students',
            field=models.ManyToManyField(through='backend.CommissionInscription', to='backend.Student', verbose_name='Alumnos Inscriptos'),
        ),
    ]
