# Generated by Django 3.1.2 on 2023-12-02 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(db_index=True, null=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actualización')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.evaluation', verbose_name='Evaluacion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Entrega de Evaluacion',
                'verbose_name_plural': 'Entregas de Evaluacion',
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationsubmission',
            constraint=models.UniqueConstraint(fields=('evaluation', 'student'), name='one_submission_per_student'),
        ),
    ]
