# Generated by Django 3.1.2 on 2023-12-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20231202_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='corrector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrector', to='backend.teacher', verbose_name='Corrector'),
        ),
    ]
