# Generated by Django 3.1.2 on 2024-01-13 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_evaluationsubmission_grader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creacion')),
                ('qrid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('owner_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances_qrs', to='backend.teacher', verbose_name='Docente que creo el QR')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qrs', to='backend.semester', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'QR de Asistencias',
                'verbose_name_plural': 'QRs de Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de escaneo')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='backend.attendanceqrcode', verbose_name='Codigo QR escaneado')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='backend.semester', verbose_name='Semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='backend.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
