# Generated by Django 3.1.2 on 2024-01-06 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_evaluationsubmission_corrector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de escaneo')),
                ('qr_generated_at', models.DateTimeField(editable=False, verbose_name='Fecha de generacion del QR escaneado')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='backend.semester', verbose_name='Semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='backend.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
