# Generated by Django 3.1.2 on 2024-02-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_attendance_attendanceqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='classes_amount',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Cantidad de Clases'),
        ),
        migrations.AddField(
            model_name='semester',
            name='minimum_attendance',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Porcentage Minimo de Asistencias'),
        ),
    ]
