# Generated by Django 3.1.2 on 2024-02-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_evaluation_parent_evaluation'),
        ('backend', '0029_auto_20240203_1926'),
    ]

    operations = [
    ]
