# Generated by Django 3.1.2 on 2024-02-17 19:58

import backend.models.attendance_qr_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_merge_20240217_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceqrcode',
            name='expires_at',
            field=models.DateTimeField(default=backend.models.attendance_qr_code.three_hours_from_now, verbose_name='Fecha de expiracion'),
        ),
    ]
