# Generated by Django 3.1.2 on 2024-02-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_attendanceqrcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrole',
            name='grader_weight',
            field=models.FloatField(default=1.0, verbose_name='Peso al asignar correctores'),
        ),
        migrations.AlterField(
            model_name='teacherrole',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_roles', to='backend.commission', verbose_name='Profesores'),
        ),
    ]
