# Generated by Django 3.1.2 on 2024-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20240324_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='chief_teacher_grader_weight',
            field=models.FloatField(default=5.0, verbose_name='Peso al asignar correctores'),
        ),
    ]
