# Generated by Django 3.1.2 on 2024-04-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_commission_chief_teacher_grader_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Registro de Auditoria', 'verbose_name_plural': 'Registro de Auditoria'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='subject_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre de Materia'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='subject_siu_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='SIU ID de Materia'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='classes_amount',
            field=models.IntegerField(blank=True, db_index=True, default=18, null=True, verbose_name='Cantidad de Clases'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='minimum_attendance',
            field=models.FloatField(blank=True, db_index=True, default=0.0, null=True, verbose_name='Porcentage Minimo de Asistencias'),
        ),
        migrations.AlterField(
            model_name='teacherrole',
            name='role',
            field=models.CharField(max_length=25, verbose_name='Rol'),
        ),
    ]
