# Generated by Django 3.1.2 on 2024-04-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20240420_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrole',
            name='role',
            field=models.CharField(max_length=30, verbose_name='Rol'),
        ),
    ]
