# Generated by Django 3.1.2 on 2026-01-12 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20240420_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google')], max_length=32)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='authidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_identity_per_provider'),
        ),
    ]
