# Generated by Django 3.1.2 on 2026-01-12 02:31

from django.db import migrations
from django.utils import timezone

def populate_auth_identities(apps, schema_editor):
    User = apps.get_model('backend', 'User')
    AuthIdentity = apps.get_model('backend', 'AuthIdentity')
    
    for user in User.objects.all():
        if AuthIdentity.objects.filter(user=user).exists():
            continue
        provider_user_id = user.dni or str(user.pk)
        AuthIdentity.objects.create(
            user=user,
            provider='local',
            provider_user_id=provider_user_id,
            email=user.email,
            added_at=user.created_at or timezone.now(),
        )

def reverse_populate(apps, schema_editor):
    AuthIdentity = apps.get_model('backend', 'AuthIdentity')
    AuthIdentity.objects.filter(provider='local').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auth_identity'),
    ]

    operations = [
        migrations.RunPython(populate_auth_identities, reverse_populate),
    ]
