# Generated by Django 3.1.2 on 2026-02-21 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_populate_auth_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='backend.teacher')),
                ('university', models.CharField(max_length=255, verbose_name='Universidad')),
                ('degree', models.CharField(max_length=255, verbose_name='Título / Carrera')),
                ('bio', models.TextField(blank=True, verbose_name='Descripción personal')),
                ('current_position', models.CharField(max_length=255, verbose_name='Cargo actual')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(70)])),
                ('certifications', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Perfil Profesional Docente',
                'verbose_name_plural': 'Perfiles Profesionales Docentes',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='padron',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^\\d{5,7}$', 'El padrón debe ser un número de entre 5 y 7 dígitos')], verbose_name='Padrón'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='backend.teacherprofile')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
