# Generated by Django 3.1.2 on 2026-02-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20260221_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='LinkedIn'),
        ),
    ]
