from .commission import Commission
from .commissionInscription import CommissionInscription
from .evaluation import Evaluation
from .evaluation_submission import EvaluationSubmission
from .final import Final
from .final_exam import FinalExam
from .semester import Semester
from .staff import Staff
from .student import Student
from .teacher import Teacher
from .teacher_role import TeacherRole
from .user import User
from .attendance import Attendance
