from .commission import Commission
from .commissionInscription import CommissionInscription
from .final import Final
from .final_exam import FinalExam
from .semester import Semester
from .staff import Staff
from .student import Student
from .teacher import Teacher
from .user import User
